### ISSUE TITLE
We need to fix the favicon

### ISSUE THREAD

**Issue by lakruzz** [Praqma/web-codeall#16] opened 2017-08-23 07:30 UTC
![image](https://user-images.githubusercontent.com/155492/29603692-66a7326e-87e5-11e7-8f3b-dde017c1088c.png)

It's [here](https://raw.githubusercontent.com/Praqma/web-codeall/master/favicon.ico)

**Comment by jonnycoull** [comment] 2017-09-22 08:27
@lakruzz there was a dupe of this in my repo. 

see here....

https://drive.google.com/open?id=0B3mqCwER-jlkZ3Rjb0g5S05jczA

**Comment by buep** [comment] 2018-06-13 08:54
Linking https://github.com/Praqma/phablework/issues/79

**Closed as completed** 2018-07-20 08:09 UTC
Labels: Size 1 - small
